/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_TPM1CH0SRC_TPM1_CH0 0x00u /*!<@brief TPM1 channel 0 input capture source select: TPM1_CH0 signal */
#define SOPT4_TPM2CH0SRC_TPM2_CH0 0x00u /*!<@brief TPM2 Channel 0 Input Capture Source Select: TPM2_CH0 signal */

/*! @name PORTE24 (number 20), U2[7]/U10[4]/I2C0_SCL/I2C_NFC_SCL
  @{ */
#define BOARD_INITPINS_I2C0_SCL_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_I2C0_SCL_PIN 24U    /*!<@brief PORTE pin index: 24 */
                                           /* @} */

/*! @name PORTE25 (number 21), U2[6]/U10[6]/I2C0_SDA/I2C_NFC_SDA
  @{ */
#define BOARD_INITPINS_I2C0_SDA_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_I2C0_SDA_PIN 25U    /*!<@brief PORTE pin index: 25 */
                                           /* @} */

/*! @name PORTD0 (number 57), LCD-09_P40/SPI_RF_SS
  @{ */
#define BOARD_INITPINS_SIGFOX_CS_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_SIGFOX_CS_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SIGFOX_CS_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                            /* @} */

/*! @name PORTD1 (number 58), U2[9]/U10[9]/INT2_ACCEL/INT1_MAG/LCD_P41/SPI_RF_SCK
  @{ */
#define BOARD_INITPINS_SIGFOX_SCK_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SIGFOX_SCK_PIN 1U     /*!<@brief PORTD pin index: 1 */
                                             /* @} */

/*! @name PORTD2 (number 59), J2[4]/D9/LCD_P42/SPI_RF_MOSI
  @{ */
#define BOARD_INITPINS_SIGFOX_SDO_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SIGFOX_SDO_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                             /* @} */

/*! @name PORTD3 (number 60), J1[6]/D2/LCD_P43/SPI_RF_MISO
  @{ */
#define BOARD_INITPINS_SIGFOX_SDI_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_SIGFOX_SDI_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                             /* @} */

/*! @name PORTD4 (number 61), J2[6]/D10/SPI1_PCS0/LCD_P44/SPI_DP_SS
  @{ */
#define BOARD_INITPINS_DP_CS_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DP_CS_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                        /* @} */

/*! @name PORTD5 (number 62), J2[12]/D13/SPI1_SCK/LED1/LCD_P45/SPI_DP_SCK
  @{ */
#define BOARD_INITPINS_DP_SCK_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DP_SCK_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                         /* @} */

/*! @name PORTD6 (number 63), J2[8]/D11/SPI1_MOSI/LCD_P46/SPI_DP_MOSI
  @{ */
#define BOARD_INITPINS_DP_DIN_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DP_DIN_PIN 6U     /*!<@brief PORTD pin index: 6 */
                                         /* @} */

/*! @name PORTE0 (number 1), J2[18]/J4[9]/D14/I2C1_SDA/CMP0_OUT/LCD_P48/NFC_RES
  @{ */
#define BOARD_INITPINS_NFC_RST_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_NFC_RST_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_NFC_RST_PIN 0U     /*!<@brief PORTE pin index: 0 */
                                          /* @} */

/*! @name PORTE1 (number 2), J2[20]/D15/I2C1_SCL/LCD_P49/~RF_RST
  @{ */
#define BOARD_INITPINS_SIGFOX_RST_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_SIGFOX_RST_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_SIGFOX_RST_PIN 1U     /*!<@brief PORTE pin index: 1 */
                                             /* @} */

/*! @name VREGIN (number 8), USB_REGIN
  @{ */
/* @} */

/*! @name PORTE31 (number 19), LED2/IN1A
  @{ */
#define BOARD_INITPINS_IN1A_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_IN1A_PIN 31U    /*!<@brief PORTE pin index: 31 */
                                       /* @} */

/*! @name PORTC5 (number 54), J1[15]/INT1_ACCEL/LCD_P25/BUTTON_1
  @{ */
#define BOARD_INITPINS_INT1_ACCEL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_INT1_ACCEL_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                             /* @} */

/*! @name PORTC6 (number 55), J1[9]/LCD_P26/BUTTON_2
  @{ */
#define BOARD_INITPINS_BUTTON_2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_BUTTON_2_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                           /* @} */

/*! @name PORTA12 (number 28), J1[8]/D3/IN1B
  @{ */
#define BOARD_INITPINS_IN1B_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_IN1B_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                       /* @} */

/*! @name PORTA13 (number 29), J2[2]/D8/IN2A
  @{ */
#define BOARD_INITPINS_IN2A_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_IN2A_PIN 13U    /*!<@brief PORTA pin index: 13 */
                                       /* @} */

/*! @name PORTB2 (number 37), J4[6]/A2/LCD_P2/IN2B
  @{ */
#define BOARD_INITPINS_IN2B_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_IN2B_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                       /* @} */

/*! @name PORTC23 (number 52), LCD_P39/RF_ACK
  @{ */
#define BOARD_INITPINS_SIGFOX_AK_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_SIGFOX_AK_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_SIGFOX_AK_PIN 23U    /*!<@brief PORTC pin index: 23 */
                                            /* @} */

/*! @name PORTC22 (number 51), LCD_P6/DP_RESET
  @{ */
#define BOARD_INITPINS_DP_RST_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_DP_RST_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_DP_RST_PIN 22U    /*!<@brief PORTC pin index: 22 */
                                         /* @} */

/*! @name PORTC21 (number 50), TP10/LCD_P5/DP_LED
  @{ */
#define BOARD_INITPINS_DP_BUSY_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_DP_BUSY_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_DP_BUSY_PIN 21U    /*!<@brief PORTC pin index: 21 */
                                          /* @} */

/*! @name PORTC20 (number 49), TP12/LCD_P4/DP_DC
  @{ */
#define BOARD_INITPINS_DP_DC_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_DP_DC_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_DP_DC_PIN 20U    /*!<@brief PORTC pin index: 20 */
                                        /* @} */

/*! @name PORTB0 (number 35), J4[2]/A0/LCD_P0/NFC_IRQ
  @{ */
#define BOARD_INITPINS_NFC_INT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_NFC_INT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_NFC_INT_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                          /* @} */

/*! @name PORTC3 (number 46), SW3/LLWU_P7/LCD_P23/BATT_C
  @{ */
#define BOARD_INITPINS_BATT_C_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_BATT_C_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_BATT_C_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                         /* @} */

/*! @name PORTC4 (number 53), J1[7]/LCD_P24/POWER_STAT
  @{ */
#define BOARD_INITPINS_POWER_STAT_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_POWER_STAT_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_POWER_STAT_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name VREGIN (number 8), USB_REGIN
  @{ */
/* @} */

/*! @name PORTC3 (number 46), SW3/LLWU_P7/LCD_P23/BATT_C
  @{ */
#define BOARD_DISABLEPINS_BATT_C_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_DISABLEPINS_BATT_C_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                            /* @} */

/*! @name PORTC4 (number 53), J1[7]/LCD_P24/POWER_STAT
  @{ */
#define BOARD_DISABLEPINS_POWER_STAT_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_DISABLEPINS_POWER_STAT_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                                /* @} */

/*! @name PORTC5 (number 54), J1[15]/INT1_ACCEL/LCD_P25/BUTTON_1
  @{ */
#define BOARD_DISABLEPINS_INT1_ACCEL_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_DISABLEPINS_INT1_ACCEL_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                                /* @} */

/*! @name PORTC6 (number 55), J1[9]/LCD_P26/BUTTON_2
  @{ */
#define BOARD_DISABLEPINS_BUTTON_2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_DISABLEPINS_BUTTON_2_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                              /* @} */

/*! @name PORTB0 (number 35), J4[2]/A0/LCD_P0/NFC_IRQ
  @{ */
#define BOARD_DISABLEPINS_NFC_INT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_DISABLEPINS_NFC_INT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_DISABLEPINS_NFC_INT_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                             /* @} */

/*! @name PORTE25 (number 21), U2[6]/U10[6]/I2C0_SDA/I2C_NFC_SDA
  @{ */
#define BOARD_DISABLEPINS_I2C0_SDA_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_DISABLEPINS_I2C0_SDA_PIN 25U    /*!<@brief PORTE pin index: 25 */
                                              /* @} */

/*! @name PORTC20 (number 49), TP12/LCD_P4/DP_DC
  @{ */
#define BOARD_DISABLEPINS_DP_DC_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_DISABLEPINS_DP_DC_PIN 20U    /*!<@brief PORTC pin index: 20 */
                                           /* @} */

/*!
 * @brief Disable output pins before going to sleep mode
 *
 */
void BOARD_DisablePins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
